### ISSUE TITLE
Should it not say Contracts with resource: Gold and year signed: 2009 in the header when searching for both? (3)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#15]

**Comment by charlesyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/13888372/10631221/b28964e2-77dc-11e5-96bc-f30220ec5c0d.png)

**Comment by charlesyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/13888372/11525747/6419f51a-98de-11e5-9e0b-3832b167f030.png)

**Comment by jerico** [comment]
This is fixed
