### ISSUE TITLE
Do we not allow for the download of contracts in Word format? (1)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#16]

**Comment by jerico** [comment]
This is fixed

**Comment by charlesyoung** [comment]
Where is the Word link, I only see the PDF download link.

**Comment by jerico** [comment]
Update download with Word file instead of HTML file

**Comment by jerico** [comment]
This is fixed

**Comment by jerico** [comment]
Check on Windows

**Comment by jerico** [comment]
I have verified that this is working on Windows using Chrome, Firefox, and Internet Explorer
