### ISSUE TITLE
Learn more link (3)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#19]
The learn more link takes the user to the RC home page which obviously needs to be redirected to an actual learn more page. 

![image](https://cloud.githubusercontent.com/assets/13888372/10481569/a889e0b8-7271-11e5-9e16-5992c38d7309.png)

**Comment by jerico** [comment]
Since our subsite have no "Learn more" page, I've temporarily omitted the link
