### ISSUE TITLE
Add front page link to ResourceContracts.org

### ISSUE THREAD

**Issue by anderspeders** [jerico/ph-eiti-contracts-portal#25]

**Comment by jerico** [comment]
NRGI logo goes to ResourceContracts.org, is this correct? @anderspeders

**Comment by anderspeders** [comment]
No, th NRGI logo should lead to: http://resourcegovernance.org/

We should however also link to the core site at RC.org. I would suggest: 

"Explore extractive contracts from across the world at resourcecontracts.org"

**Comment by jerico** [comment]
This is now updated

**Comment by charlesyoung** [comment]
Fixed, @anderspeders pls close the case.
