### ISSUE TITLE
Free text search missing from contract overview

### ISSUE THREAD

**Issue by anderspeders** [jerico/ph-eiti-contracts-portal#26]
![image](https://cloud.githubusercontent.com/assets/1101585/10483572/27080cea-724e-11e5-968d-0b5707f90a78.png)

**Comment by charlesyoung** [comment]
Allow for free text search from the contract overview as this is currently only provided on the home page. 

![image](https://cloud.githubusercontent.com/assets/13888372/10631008/2baf2d36-77db-11e5-94e7-f6af414b9984.png)

Also the only way to view all contracts is from the home page. Should this option not be added to above?  

![image](https://cloud.githubusercontent.com/assets/13888372/10631034/6479ad6c-77db-11e5-833b-b79243349a7b.png)

**Comment by jerico** [comment]
Change "search" placeholder, remove "location"
