### ISSUE TITLE
Advisory on open data licensing and Terms of Service

### ISSUE THREAD

**Issue by anderspeders** [jerico/ph-eiti-contracts-portal#27]

**Comment by anderspeders** [comment]
Please provide language on the front page: 

All content on the site is available as open data under Creative Commons Attribution 3.0 [LINK: http://opendefinition.org/licenses/cc-by/] in accordance with the recommendations in the Open Data Philippines Action Plan 2014-2016 [LINK: http://www.gov.ph/downloads/2014/01jan/Open-Data-Philippines-Action-Plan-2014-2016.pdf]

Source code for the site is avalable here [LINK: https://github.com/NRGI/resourcecontracts.org]

Please double check this language with Gay.

**Comment by charlesyoung** [comment]
Fixed, @anderspeders pls close the case.
