### ISSUE TITLE
Selections (1)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#33]
Selecting a resource or year from the side bar displays no results.

**Comment by jerico** [comment]
This was an issue with API not reliably returning contract details. API endpoint has been updated c/o Anjesh.

This is fixed.

**Comment by charlesyoung** [comment]
The searching is still very slow.

**Comment by charlesyoung** [comment]
Issue back again. Searching for year from the side bar. 

![image](https://cloud.githubusercontent.com/assets/13888372/10606669/c924bf4c-7734-11e5-9a69-0d1b42b515b7.png)
