### ISSUE TITLE
Remove front page text hyperlink (2) 

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#35]
Below front page text is hyperlinked to open all the contracts. 

![image](https://cloud.githubusercontent.com/assets/13888372/10540752/281e1430-740b-11e5-9ecc-755538407414.png)

**Comment by jerico** [comment]
This was requested by PH-EITI. Their initial action when visiting the site was to click on the big title text. Do you think this is unnecessary?

**Comment by charlesyoung** [comment]
Must say that as an user I wouldn't expect the text to be hyperlinked. Also its not clear where the page will be redirected to.
