### ISSUE TITLE
Add: "With support from" + DFID logo

### ISSUE THREAD

**Issue by anderspeders** [jerico/ph-eiti-contracts-portal#39]
Add: "Created with support from"

Insert DFID logo following the guidelines: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/326391/UK_aid_branding_guidance_June_2014.pdf

**Comment by jerico** [comment]
This is implemented, please confirm

**Comment by charlesyoung** [comment]
Fixed, @anderspeders pls close the case.
