### ISSUE TITLE
Capitalisation issues (2)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#4]
Capitalisation issues as noted below. 

![image](https://cloud.githubusercontent.com/assets/13888372/10337473/30584f56-6d00-11e5-985c-7f30f17a1025.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10337516/6d0cb144-6d00-11e5-95be-01fdd4facb9d.png)

**Comment by jerico** [comment]
This is fixed

**Comment by jerico** [comment]
We haven't closed this one because it is an issue with the API. I just checked the API and this is now fixed. 

<img width="278" alt="screen shot 2015-10-17 at 17 15 20" src="https://cloud.githubusercontent.com/assets/1062325/10557990/d54e315c-74f2-11e5-999c-b21b58efa2ed.png">
