### ISSUE TITLE
Full browser review

### ISSUE THREAD

**Issue by anderspeders** [jerico/ph-eiti-contracts-portal#40]
Can we runa full rbowser review of the site based on: 
- Firefox
- Safari
- Chrome
- IE

**Comment by charlesyoung** [comment]
Mainly been working on Chrome without issues. Also did basic tests using IE and Safari without any issues.

**Comment by jerico** [comment]
I've also tested on Firefox, Safari, Chrome, IE, and Edge. 

However, I haven't tested on tablet and mobile devices yet.
