### ISSUE TITLE
Company name incorrect

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#43]
Can you ask Joy to remove all additional text in the company name as shown below. This needs to change because the search crashes if the name includes a bracket. 

![image](https://cloud.githubusercontent.com/assets/13888372/10630566/bcda4970-77d7-11e5-8d06-6bdbecd3e9bb.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10630621/3232f42e-77d8-11e5-8b4d-569aa67810a3.png)

![image](https://cloud.githubusercontent.com/assets/13888372/10630699/e65b21f6-77d8-11e5-9900-417596bdf6b1.png)

**Comment by jerico** [comment]
I got a word from Joy that this has been fixed
