### ISSUE TITLE
Company duplicate

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#46]
Duplicate company name. 

![image](https://cloud.githubusercontent.com/assets/13888372/10633259/de5eb5f6-77e9-11e5-87fe-b53d1ddc1798.png)

**Comment by anderspeders** [comment]
@jerico This could very likely be due to an extra space or similar - which generates two uniqe ids instead of one.

**Comment by charlesyoung** [comment]
A question; why is the and in capitals on the PH site while its not on the RC site and admin module?

**Comment by charlesyoung** [comment]
Fixed, there was an additional space on one of the contract names.

**Comment by jerico** [comment]
Yes, a simple space or comma will make the company appear twice

**Comment by charlesyoung** [comment]
What about the capital And in the company name?
