### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#47]
![image](https://cloud.githubusercontent.com/assets/13888372/10634415/e8c368cc-77f1-11e5-9938-73841a0fa22f.png)

**Comment by anderspeders** [comment]
Site is down for me as well. 

@jerico Can you check on this?

**Comment by charlesyoung** [comment]
Site is up again but @jerico we need to find out why it went down.

**Comment by jerico** [comment]
This has happened to me as I was modifying the site. I think I have an idea.

When we are browsing the site in a fast succession, the server is configured to block the IP. 

I have reported this to our hosting company and it has been immediately resolved. However, I'm still asking a guarantee from them that this should not happen especially on launch date. I'm still waiting for their reply.
