### ISSUE TITLE
Companies vs resources (1)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#48]
Seems like Forum Exploration is only an oil / gas company although they are listed under mining companies in the side bar.

**Comment by jerico** [comment]
This is an effect of hard-coding Oil and Gas companies. I'll be able to fix this post-launch. For the mean time, I'll manually remove Forum Exploration under Oil and Gas

**Comment by charlesyoung** [comment]
OK but we need to change the hard-coding routine soonish as discussed because this will create problems going forward.
