### ISSUE TITLE
Different presentation (2)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#5]
The resource list presentation is different when clicking on all contracts vs. when clicking on a specific resource from the side bar.

**Comment by jerico** [comment]
This is fixed

**Comment by jerico** [comment]
Consolidating of "Oil" and "Gas" and separating those to "Mining" was request of PH-EITI.

"Oil and Gas" is moved to the bottom in "All contracts" as we have discussed.

**Comment by charlesyoung** [comment]
Can you move oil and gas to the bottom but separate with the mining resources with a line?

**Comment by charlesyoung** [comment]
Can we not rather make it alphabetical?
