### ISSUE TITLE
Searching reset option

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#52]
Include a searching reset option like the RC site. 

![image](https://cloud.githubusercontent.com/assets/13888372/11422733/19cda5f6-9447-11e5-8b7f-8d72caab182e.png)

**Comment by charlesyoung** [comment]
Move reset button. 

![image](https://cloud.githubusercontent.com/assets/13888372/11525526/8188648a-98dc-11e5-8fa4-6a2a7d395784.png)

**Comment by charlesyoung** [comment]
Also the reset shouldn't then show all the contracts.

**Comment by jerico** [comment]
Reset has been repositioned. It will now just reset all fields to default.
