### ISSUE TITLE
Year selection

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#54]
Sort year selection list 

![image](https://cloud.githubusercontent.com/assets/13888372/11423771/f4b4577a-944f-11e5-900d-8a8228cb60f7.png)

**Comment by jerico** [comment]
@charlesyoung This is fixed, please confirm

**Comment by charlesyoung** [comment]
Thanks but can you start with the most recent (2011) on top of the list and not the other way round.

**Comment by charlesyoung** [comment]
Still need to show the most recent date first.

**Comment by jerico** [comment]
This is now adjusted to show recent date first @charlesyoung
