### ISSUE TITLE
Link doesnt work

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#57]
![image](https://cloud.githubusercontent.com/assets/13888372/11528820/c283bc4a-98f1-11e5-8571-72fa4913610c.png)

**Comment by jerico** [comment]
Link is working on my end. Their server might be down at time of testing.

**Comment by charlesyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/13888372/11550630/4fe7bcb6-997a-11e5-988d-761e46150562.png)
