### ISSUE TITLE
Should the contractor and operator description be included in the company name? (2)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#9]

**Comment by jerico** [comment]
With the request of PH-EITI to use contract name as company name, this has been addressed as well.

https://github.com/jerico/ph-eiti-contracts-portal/issues/31

**Comment by jerico** [comment]
This will be removed on actual metadata as requested by Anders (via email). I will update this issue once contract metadata are update.
